package com.example.mybatis.demo.domain;

import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@EqualsAndHashCode
public class Account implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.id
     *
     * @mbg.generated Tue Aug 20 18:52:04 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.user_id
     *
     * @mbg.generated Tue Aug 20 18:52:04 CST 2019
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.info
     *
     * @mbg.generated Tue Aug 20 18:52:04 CST 2019
     */
    private String info;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.ctime
     *
     * @mbg.generated Tue Aug 20 18:52:04 CST 2019
     */
    private Long ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.utime
     *
     * @mbg.generated Tue Aug 20 18:52:04 CST 2019
     */
    private Long utime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account
     *
     * @mbg.generated Tue Aug 20 18:52:04 CST 2019
     */
    private static final long serialVersionUID = 1L;


}