package com.example.mybatis.demo.domain;


import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@EqualsAndHashCode
public class MUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.id
     *
     * @mbg.generated Tue Aug 20 12:22:31 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.name
     *
     * @mbg.generated Tue Aug 20 12:22:31 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.pwd
     *
     * @mbg.generated Tue Aug 20 12:22:31 CST 2019
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.email
     *
     * @mbg.generated Tue Aug 20 12:22:31 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.phone
     *
     * @mbg.generated Tue Aug 20 12:22:31 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_user.address
     *
     * @mbg.generated Tue Aug 20 12:22:31 CST 2019
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_user
     *
     * @mbg.generated Tue Aug 20 12:22:31 CST 2019
     */
    private static final long serialVersionUID = 1L;



}