package com.example.mybatis.demo.domain;

import java.io.Serializable;
import java.math.BigDecimal;

public class UOrder implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_order.id
     *
     * @mbg.generated Tue Aug 20 18:34:29 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_order.user_id
     *
     * @mbg.generated Tue Aug 20 18:34:29 CST 2019
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_order.name
     *
     * @mbg.generated Tue Aug 20 18:34:29 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_order.price
     *
     * @mbg.generated Tue Aug 20 18:34:29 CST 2019
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_order.order_list
     *
     * @mbg.generated Tue Aug 20 18:34:29 CST 2019
     */
    private String orderList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_order.ctime
     *
     * @mbg.generated Tue Aug 20 18:34:29 CST 2019
     */
    private Long ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_order.utime
     *
     * @mbg.generated Tue Aug 20 18:34:29 CST 2019
     */
    private Long utime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table u_order
     *
     * @mbg.generated Tue Aug 20 18:34:29 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_order.id
     *
     * @return the value of u_order.id
     *
     * @mbg.generated Tue Aug 20 18:34:29 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_order.id
     *
     * @param id the value for u_order.id
     *
     * @mbg.generated Tue Aug 20 18:34:29 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_order.user_id
     *
     * @return the value of u_order.user_id
     *
     * @mbg.generated Tue Aug 20 18:34:29 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_order.user_id
     *
     * @param userId the value for u_order.user_id
     *
     * @mbg.generated Tue Aug 20 18:34:29 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_order.name
     *
     * @return the value of u_order.name
     *
     * @mbg.generated Tue Aug 20 18:34:29 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_order.name
     *
     * @param name the value for u_order.name
     *
     * @mbg.generated Tue Aug 20 18:34:29 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_order.price
     *
     * @return the value of u_order.price
     *
     * @mbg.generated Tue Aug 20 18:34:29 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_order.price
     *
     * @param price the value for u_order.price
     *
     * @mbg.generated Tue Aug 20 18:34:29 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_order.order_list
     *
     * @return the value of u_order.order_list
     *
     * @mbg.generated Tue Aug 20 18:34:29 CST 2019
     */
    public String getOrderList() {
        return orderList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_order.order_list
     *
     * @param orderList the value for u_order.order_list
     *
     * @mbg.generated Tue Aug 20 18:34:29 CST 2019
     */
    public void setOrderList(String orderList) {
        this.orderList = orderList == null ? null : orderList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_order.ctime
     *
     * @return the value of u_order.ctime
     *
     * @mbg.generated Tue Aug 20 18:34:29 CST 2019
     */
    public Long getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_order.ctime
     *
     * @param ctime the value for u_order.ctime
     *
     * @mbg.generated Tue Aug 20 18:34:29 CST 2019
     */
    public void setCtime(Long ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_order.utime
     *
     * @return the value of u_order.utime
     *
     * @mbg.generated Tue Aug 20 18:34:29 CST 2019
     */
    public Long getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_order.utime
     *
     * @param utime the value for u_order.utime
     *
     * @mbg.generated Tue Aug 20 18:34:29 CST 2019
     */
    public void setUtime(Long utime) {
        this.utime = utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_order
     *
     * @mbg.generated Tue Aug 20 18:34:29 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UOrder other = (UOrder) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()))
            && (this.getOrderList() == null ? other.getOrderList() == null : this.getOrderList().equals(other.getOrderList()))
            && (this.getCtime() == null ? other.getCtime() == null : this.getCtime().equals(other.getCtime()))
            && (this.getUtime() == null ? other.getUtime() == null : this.getUtime().equals(other.getUtime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_order
     *
     * @mbg.generated Tue Aug 20 18:34:29 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
        result = prime * result + ((getOrderList() == null) ? 0 : getOrderList().hashCode());
        result = prime * result + ((getCtime() == null) ? 0 : getCtime().hashCode());
        result = prime * result + ((getUtime() == null) ? 0 : getUtime().hashCode());
        return result;
    }
}