package com.example.mybatis.demo.mapper;

import com.example.mybatis.demo.domain.UOrder;
import org.apache.ibatis.jdbc.SQL;

public class UOrderSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_order
     *
     * @mbg.generated Tue Aug 20 18:34:29 CST 2019
     */
    public String insertSelective(UOrder record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("u_order");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            sql.VALUES("user_id", "#{userId,jdbcType=BIGINT}");
        }
        
        if (record.getName() != null) {
            sql.VALUES("name", "#{name,jdbcType=VARCHAR}");
        }
        
        if (record.getPrice() != null) {
            sql.VALUES("price", "#{price,jdbcType=NUMERIC}");
        }
        
        if (record.getOrderList() != null) {
            sql.VALUES("order_list", "#{orderList,jdbcType=VARCHAR}");
        }
        
        if (record.getCtime() != null) {
            sql.VALUES("ctime", "#{ctime,jdbcType=BIGINT}");
        }
        
        if (record.getUtime() != null) {
            sql.VALUES("utime", "#{utime,jdbcType=BIGINT}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_order
     *
     * @mbg.generated Tue Aug 20 18:34:29 CST 2019
     */
    public String updateByPrimaryKeySelective(UOrder record) {
        SQL sql = new SQL();
        sql.UPDATE("u_order");
        
        if (record.getUserId() != null) {
            sql.SET("user_id = #{userId,jdbcType=BIGINT}");
        }
        
        if (record.getName() != null) {
            sql.SET("name = #{name,jdbcType=VARCHAR}");
        }
        
        if (record.getPrice() != null) {
            sql.SET("price = #{price,jdbcType=NUMERIC}");
        }
        
        if (record.getOrderList() != null) {
            sql.SET("order_list = #{orderList,jdbcType=VARCHAR}");
        }
        
        if (record.getCtime() != null) {
            sql.SET("ctime = #{ctime,jdbcType=BIGINT}");
        }
        
        if (record.getUtime() != null) {
            sql.SET("utime = #{utime,jdbcType=BIGINT}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}